### ISSUE TITLE
1.9.5: Fatal error when injecting a CSV

### ISSUE THREAD

**Issue by pVesian** [pluginsGLPI/order#91]
Hi,

When injecting a CSV using the datainjection plugin it fails because of this error below. I'm using GLPI 9.1.1 with data injection 2.4.2. It looks like #67, but I tried with the master branch and the bug is the same. Attached a CSV example.

```
PHP Notice: Undefined index: PluginOrderOrderInjection in /var/www/html/glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 234
PHP Notice: Undefined index: PluginOrderOrderInjection in /var/www/html/glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 1713
PHP Warning: Invalid argument supplied for foreach() in /var/www/html/glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 1713
PHP Notice: Trying to get property of non-object in /var/www/html/glpi/inc/dbmysql.class.php at line 268

Fatal error: Uncaught Error: Class 'PluginOrderOrderInjectionInjection' not found in /var/www/html/glpi/plugins/datainjection/inc/commoninjectionlib.class.php:326
Stack trace:
#0 /var/www/html/glpi/plugins/datainjection/inc/commoninjectionlib.class.php(901): PluginDatainjectionCommonInjectionLib::getInjectionClassInstance('PluginOrderOrde...')
#1 /var/www/html/glpi/plugins/datainjection/inc/commoninjectionlib.class.php(983): PluginDatainjectionCommonInjectionLib->reformatFirstPass()
#2 /var/www/html/glpi/plugins/datainjection/inc/commoninjectionlib.class.php(1394): PluginDatainjectionCommonInjectionLib->reformat()
#3 /var/www/html/glpi/plugins/order/inc/orderinjection.class.php(57): PluginDatainjectionCommonInjectionLib->processAddOrUpdate()
#4 /var/www/html/glpi/plugins/datainjection/inc/engine.class.php(145): PluginOrderOrderInjection->addOrUpdateObject(Array, Array)
#5 /var/www/html/glpi/plugins/datainjection/inc/clientinjection.class.php(249): PluginDatainjectionEngine->injectLine(Array, 2)
#6 /var/www/html/glpi/plugi in /var/www/html/glpi/plugins/datainjection/inc/commoninjectionlib.class.php on line 326
```

Thanks

[GLPI-Commandes.csv.zip](https://github.com/pluginsGLPI/order/files/711463/GLPI-Commandes.csv.zip)

**Comment by dr-redoute** [comment]
Try to apply manually the patch I proposed for dev branch (https://github.com/pluginsGLPI/order/pull/79)

**Comment by pVesian** [comment]
I did, I got a `Parse error: syntax error, unexpected '  ' (T_STRING), expecting function (T_FUNCTION) in /var/www/html/glpi/plugins/order/inc/orderinjection.class.php on line 38`, which is weird because it's whitespace.

**Comment by trasher** [comment]
Hi, you said you tried with the master branch; but this one does not yat contains the fix; you should have tried on the develop branch.

Anyways, we're going to relese a new version very soon, your isse should be fixed in it.
